### ISSUE TITLE
導入不了

### ISSUE THREAD

**Issue by EMK2000** [WitherZuo/rx-cleanmaster-services#1]
這個導入不了，說 invalid

**Comment by WitherZuo** [comment]
抱歉，因为连续打错了好几个“”，导致处方格式不被绿色守护所认可。
这个处方已经重写了，您可以看看能否导入，如果不行我再修改，谢谢反馈！
PS：您是在酷安上发布我处方链接的用户吗？

**Comment by EMK2000** [comment]
對…原來大神有上酷安？
